### ISSUE TITLE
Please use proper data structure to hold students / rooms (O(n + m) expected)

### ISSUE THREAD

**Issue by vitalk** [ilyaborodin/LeverX_task_1#1]
https://github.com/ilyaborodin/LeverX_task_1/blob/e9aa6989e4cf8d5c5fbba28ae7a3ba50fd68dd4b/RoomWorker.py#L15

Complexity is O(n x m) because 

for student in students:  # O(m)
    if student in rooms:  # <!- rooms is a list, linear search in list is O(n)
      pass

**Comment by ilyaborodin** [comment]
Fixed
